[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
  "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
  ". /opt/venv/bin/activate && pip install -r requirements-ml.txt"
]

[start]
cmd = "chmod +x start.sh && ./start.sh"

[variables]
PORT = "3000"
